### ISSUE TITLE
moment.default(...).tz is not a function and installation problems

### ISSUE THREAD

**Issue by igorpreston** [alphasights/ember-calendar#16]
Hello,

I tried installing this addon with `ember install ember-calendar` but dependencies are not correctly installed with it and the problem with broccoli-sass and broccoli-merge-trees pop ups.
I tried installing directly from git repository: `npm install https://github.com/alphasights/ember-calendar` and then cd'ing into the _node_modules/ember-calendar_ and running npm install, though still not all dependencies are installed because it didn't copied bower.json over git. So I git cloned repo and installed dependencies with npm install and bower install.

After that, I put an example component on web page and it fails saying exactly this:
__TypeError: moment.default(...).tz is not a function (vendor.js)__
I searched through vendor.js and there is no line like that, only __moment.setDefault__.

What's the problem? I cannot use it. Installation process is greatly broken, dependencies are not auto-installing correctly and if I manually install everything - this still not works.

**Comment by willrax** [comment]
Thanks for reporting this. Will look in to it.

**Comment by igorpreston** [comment]
@willrax Thanks for quick reply! I am looking forward to fix because I really liked the calendar widget itself and want to incorporate this addon in some big project that is currently in development.

**Comment by matteodepalo** [comment]
@igorpreston Have you tried running `ember generate ember-calendar`?

**Comment by igorpreston** [comment]
@matteodepalo 
Created an empty app and did things in following sequence:
1. ember install ember-calendar
2. ember generate ember-calendar
3. Tried running app and it throwed an error that __broccoli-sass__ is required. Ok, installed broccoli-sass.
4. After rebooting app, the error in console: _Error: Could not find module `moment` imported from `ember-moment/helpers/moment`_
5. Tried running npm install and bower install but nothing has been installed.
6. Tried ember install ember-moment. It installed some bower packages.
7. After rebooting app, the error in the console: _TypeError: this.get(...) is undefined (vendor.js (line 108780, col 13))_

Can someone please provide __detailed__ instruction how to install it and get it to work without any errors.

**Comment by matteodepalo** [comment]
@eugeniodepalo would you be able to help on this? I remember you were talking about some issues with dependencies not being installed.

**Comment by e-karma** [comment]
@eugeniodepalo @matteodepalo @willrax Hello Everybody, Great work on the addon!! 
Very clean implementation.  I am however encountering the same issue...  

Any News?

Thanks!!

**Comment by matteodepalo** [comment]
Working on it https://github.com/alphasights/ember-calendar/pull/17

**Comment by matteodepalo** [comment]
The PR is ready for review. In the meanwhile if you want to help test this you can run:

- `ember new calendar-test`
- `cd calendar-test`
- `npm install "git+ssh://git@github.com:alphasights/ember-calendar.git#feature/mde/fix-dependencies" --save-dev`
- `ember generate ember-calendar`

At this point if you include the basic {{as-calendar}} component in application.hbs you should see the calendar without styles. As mentioned in the README if you want the default styles you have to install `ember-cli-paint`. A PR https://github.com/alphasights/ember-cli-paint/pull/48 is being reviewed on that repo right now and it will bump dependencies too, fixing an issue with the dropdown.

**Comment by igorpreston** [comment]
@matteodepalo did exactly as you described and included this component.
The only error I experienced is after running ember serve, it said that there is no app.scss file. I changed app.css to app.scss and worked. However:

```
{{as-calendar
  title="Ember Calendar"
  occurrences=occurrences
  defaultTimeZoneQuery="New York|London|Dubai|Hong Kong"
  dayStartingTime="9:00"
  dayEndingTime="18:00"
  timeSlotDuration="00:30"
  onAddOccurrence="calendarAddOccurrence"
  onUpdateOccurrence="calendarUpdateOccurrence"
  onRemoveOccurrence="calendarRemoveOccurrence"}}
```
Then got an error in console:
```
TypeError: this.get(...) is undefined (vendor.js (line 108660, col 13))
```

I tried removing all properties on component and did this:
```
{{as-calendar}}
```
Got an error: 
```
TypeError: this.get(...) is null (vendor.js (line 108660, col 13))
```

**Comment by matteodepalo** [comment]
Did you add the basic application controller as stated in the readme?

```
// app/controllers/index.js

import Ember from 'ember';

export default Ember.Controller.extend({
  occurrences: Ember.A(),

  actions: {
    calendarAddOccurrence: function(occurrence) {
      this.get('occurrences').pushObject(Ember.Object.create({
        title: occurrence.get('title'),
        startsAt: occurrence.get('startsAt'),
        endsAt: occurrence.get('endsAt')
      }));
    },

    calendarUpdateOccurrence: function(occurrence, properties) {
      occurrence.setProperties(properties);
    },

    calendarRemoveOccurrence: function(occurrence) {
      this.get('occurrences').removeObject(occurrence);
    }
  }
});
```

**Comment by matteodepalo** [comment]
That's mostly needed for the occurences array which is otherwise undefined.

**Comment by matteodepalo** [comment]
Version 0.1.4 is out, fixing the dependency issues you've found. I'm going to close this but feel free to open another issue if you encounter other problems!
