### ISSUE TITLE
Merge error: file app.scss exists

### ISSUE THREAD

**Issue by igorpreston** [alphasights/ember-calendar#18]
The last PR for dependency fix works just fine if installing ember-calendar into empty app. But tried to integrate ember-calendar with existing one and got this error
```
Merge error: file app.scss exists in /home/igor/calendar-test/tmp/broccoli_merge_trees-input_base_path-CN7C4cU6.tmp/4 and /home/igor/calendar-test/tmp/broccoli_merge_trees-input_base_path-CN7C4cU6.tmp/32
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
```

I was using ember-cli-sass, but ember-calendar forced to install broccoli-sass. The error stayed however. I removed ember-cli-sass in favor of broccoli-sass but same story.
I don't know where to pass { overwrite: true } to mergeTrees and if this will fix the issue.

**Comment by matteodepalo** [comment]
Thank you for reporting this, I'm planning to work on migrating the styles to `ember-cli-sass`. That should solve this issue.

**Comment by matteodepalo** [comment]
In the meanwhile since styles are optional you could try to adapt the current styles of the addon to your app by taking inspiration from the styles in the app/styles folder. I know it's not ideal, but it will be temporary.

**Comment by igorpreston** [comment]
@matteodepalo The problem is I didn't include any styles in the app for ember-calendar. After installing calendar with ember install ember-calendar and installing broccoli-sass, it fails with this error.
I can't boot the up with ember-calendar installed.

**Comment by matteodepalo** [comment]
It could be that we're conflicting with a particular file structure, as for one of our apps it works without causing troubles. I believe migrating to ember-cli-sass should give us an isolated environment that should cause less issues.

**Comment by matteodepalo** [comment]
Could you share an example app that has this issue? That would help me solve it.

**Comment by igorpreston** [comment]
@matteodepalo sure, here is the example app with ember-cli-sass installed first, and then ember-calendar added with broccoli-sass. Fails to boot.

https://github.com/igorpreston/ember-calendar-error

**Comment by matteodepalo** [comment]
Thank you! I'll take a look into it as soon as possible.

**Comment by igorpreston** [comment]
@matteodepalo hi, any news about the fix? Really looking forward into it.

**Comment by matteodepalo** [comment]
Hi sorry I haven't had the time to look into this, I'll try to find some time this week.

**Comment by matteodepalo** [comment]
I've cloned your repo and after installing everything I've got this error:

```
/Users/matteodepalo/Documents/Projects/ember-calendar-error/tmp/broccoli_merge_trees-output_path-d8M0wT5w.tmp/app/styles/app.[scss|sass] does not exist
```

I then deleted the `ember-cli-sass` line from the package json and the page rendered correctly. Could it be an issue with npm cache?

**Comment by igorpreston** [comment]
@matteodepalo you're right, `npm cache clear` did the job for that repo, but not in the production app. 
I removed ember-cli-sass and ran npm cache clear.
The error stays:
```
Merge error: file app.scss exists in /home/igor/dev/ewd/app/tmp/broccoli_merge_trees-input_base_path-1z3hbnQU.tmp/4 and /home/igor/dev/ewd/app/tmp/broccoli_merge_trees-input_base_path-1z3hbnQU.tmp/31
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
Error: Merge error: file app.scss exists in /home/igor/dev/ewd/app/tmp/broccoli_merge_trees-input_base_path-1z3hbnQU.tmp/4 and /home/igor/dev/ewd/app/tmp/broccoli_merge_trees-input_base_path-1z3hbnQU.tmp/31
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
```

**Comment by matteodepalo** [comment]
It seems that `ember-cli-sass` and `broccoli-sass` have incompatibilities that I didn't expect. I would prefer to take some time to migrate to `ember-cli-sass` which seems to be the option most people use. The only problem I have is that it's not clear how to use `ember-cli-sass` and avoid the automatic inclusion of the addon stylesheets into the application vendor.css. I'll investigate and report back once I've found a solution.

**Comment by matteodepalo** [comment]
From this issue https://github.com/ember-cli/ember-cli/pull/3344 it looks like `ember-cli-sass` doesn't currently allow us to put styles in `app/styles` and make them opt-in. Once that's fixed I can give this migration a try.

**Comment by igorpreston** [comment]
@matteodepalo hey, we must proceed forward with a hack in place for ember-cli-sass that should enable the calendar update to work.  https://github.com/aexmachina/ember-cli-sass/pull/57/files

Can you guide me or share code on what needs to be done assuming the ember-cli-sass issue was solved?  We have an important client we must demonstrate calendar for later today.

**Comment by matteodepalo** [comment]
If you're looking for workarounds I suggest checking the linked issue in ember-cli.

**Comment by sandstrom** [comment]
Possibly this is solved now: https://github.com/ember-cli/ember-cli/pull/4825#issuecomment-144107098

**Comment by Arkham** [comment]
Although there is still an incompatibility between broccoli-sass and ember-cli-sass, if you remove ember-cli-sass and run npm install, everything will work fine. I'll close the issue, feel free to reopen if the problem pops up again.
