### ISSUE TITLE
Large non-scoped CSS Stylesheet make integrating into a larger app a hastle

### ISSUE THREAD

**Issue by rb2020** [alphasights/ember-calendar#19]
Any ideas as to how to integrate the 5k lines of CSS into a larger existing app?  I'm personally a fan of the design and would prefer to prevent bleeding versus full-scale rip and replacement.  

The only thing I can come up with is filtering the calendar through an addon such as this => https://github.com/ebryn/ember-component-css where it scopes the CSS. 

Thoughts? Have you dealt with / overcame this problem at all?

**Comment by Arkham** [comment]
Hey @rb2020, we are planning to release a new version which doesn't depend on the css framework we use internally. Stay tuned!

**Comment by jcowley** [comment]
+1 This is a great component, but I think the inclusion of the global CSS would be a non starter for anyone using this component in any app. It completely changes the style of the entire site.

I love the component and the code is beautiful. But that 5K lines of CSS... whew. Trying to decide now whether it's feasible to rebuild the CSS from the ground up so that I can use it.

**Comment by jcowley** [comment]
Hi @Arkham,

I'm working on a couple things in a fork:

1. Eliminating dependency on paint (and adding back minimal styles required for the calendar component)
2. Wrap component in top-level css class
3. Eliminate all global styles (all styles assigned to classes used by the component)

I'd love to submit this back as a PR, but wanted to get some feedback on this approach. It's not quite finished yet, but you can see the changes in progress here: https://github.com/jcowley/ember-calendar/tree/issue-19-styles

Do you see any potential issues?

Thanks.

**Comment by Arkham** [comment]
Hey @jcowley that's exactly what we are planning to do :dancer:

In addition to that, we want to BEMify the whole addon. Unfortunately, our CSS wizard @deioo has been away for some time, but here is the PR where he started the transition: https://github.com/alphasights/ember-calendar/pull/31

Hopefully by the end of the week we should have a beta version with paint removed :)

**Comment by jcowley** [comment]
Ok, great. I'll look for that beta.

Thank you!

**Comment by Arkham** [comment]
Hey @jcowley @rb2020 we just released `v0.3.0` which removes the paint dependency and bemifies the addon! Let me know if everything is working properly :)

**Comment by jcowley** [comment]
@Arkham: 

Looks really good. I did find a few small issues.

1. Build problems with font awesome. I put up PR https://github.com/alphasights/ember-calendar/pull/32 for that.
2. There are still a handful of global styles that are being imported by 'addons/ember-calendar/main' (specifically in the _global.scss file). The root element font-size is being set, among other things. I'd be happy to submit a PR for that, but I expect @deioo would have the best idea on how to fix it.

Thank you for the all the work and a great component. I'm using it now in my app and it's been fantastic.

**Comment by deioo** [comment]
@jcowley you're right, we're going to move these resets to the dummy app so the component won't inherit them by default. I'll link it to the issue once a new release is online.

**Comment by Arkham** [comment]
@jcowley just released `0.3.1` which includes all the fixes :) :confetti_ball:

**Comment by jcowley** [comment]
Tried the new version and it's working well for me. Seems like this issue can be closed.

Thank you again. Great component!
