### ISSUE TITLE
Could not find module `moment` imported from `ember-calendar/macros/computed-moment`

### ISSUE THREAD

**Issue by blaedj** [alphasights/ember-calendar#25]
This may be related to #16, or at least a similar problem, I'm not sure. 

### Repro Steps: 

 1. `ember new calendar-test`
 2. `ember install ember-calendar`
 3. `ember generate ember-calendar`
 4.  rename `app/styles/app.css` to `app/styles/app.scss`
 5. add `{{as-calendar}}` to `app/templates/application.hbs`
 6. run `ember serve` and view in browser, an error is shown in the console:    

         Could not find module `moment` imported from `ember-calendar/macros/computed-moment`

if it helps, here is a diff of all the changes made from the clean `ember new` generated app: https://gist.github.com/blaedj/277d878ae0987e99cacb

I'm Using ember-cli 1.13.13. If there is any more info that would be useful or any way I can help with this let me know!

**Comment by Arkham** [comment]
Hey @blaedj, thanks so much for reporting this! I've released version `0.1.8` of the addon, which should fix all the issues.

Here's what I did to have it working:

1. `ember new calendar-test && cd calendar-test`
2. `ember install ember-calendar`
3. `ember install ember-cli-paint`, this is only needed if you want to use our styles
4. Add some standard code in the following files:

`app/controllers/index.js`
```js
import Ember from 'ember';

export default Ember.Controller.extend({
  occurrences: Ember.A(),

  actions: {
    calendarAddOccurrence: function(occurrence) {
      this.get('occurrences').pushObject(Ember.Object.create({
        title: occurrence.get('title'),
        startsAt: occurrence.get('startsAt'),
        endsAt: occurrence.get('endsAt')
      }));
    },

    calendarUpdateOccurrence: function(occurrence, properties) {
      occurrence.setProperties(properties);
    },

    calendarRemoveOccurrence: function(occurrence) {
      this.get('occurrences').removeObject(occurrence);
    }
  }
});
```

`app/templates/index.hbs`
```hbs
{{as-calendar
  title="Ember Calendar"
  occurrences=occurrences
  defaultTimeZoneQuery="New York|London|Dubai|Hong Kong"
  dayStartingTime="9:00"
  dayEndingTime="18:00"
  timeSlotDuration="00:30"
  onAddOccurrence="calendarAddOccurrence"
  onUpdateOccurrence="calendarUpdateOccurrence"
  onRemoveOccurrence="calendarRemoveOccurrence"}}
```

`app/styles/app.scss`
```scss
@import 'bower_components/paint/paint';
@import 'addons/ember-calendar/main';
```

Let me know if this new release solves your problem!

**Comment by blaedj** [comment]
Hi @Arkham, this fixed it for me thank you!

**Comment by Arkham** [comment]
Great, closing then!
