### ISSUE TITLE
Uncaught TypeError: (0 , _moment.default)(...).tz is not a function in a newly created ember app 

### ISSUE THREAD

**Issue by elhachimi** [alphasights/ember-calendar#37]
Here is what i get
<img width="1264" alt="screen shot 2016-03-04 at 2 58 45 pm" src="https://cloud.githubusercontent.com/assets/3928471/13530559/d206752e-e219-11e5-98e4-26ae0093f7c7.png">

**Comment by Arkham** [comment]
Hi @elhachimi,

thanks for reporting this, I've included the fix in the README. Inside your ENV configuration add

```js
moment: {
  includeTimezone: 'all'
}
```

**Comment by Arkham** [comment]
Nevermind, I figured out a way which doesn't require the user to change the config manually. Just install `0.3.4` and everything should be fine :)

**Comment by elhachimi** [comment]
Seams to work fine :+1:  , awesome thanks a lot .
