### ISSUE TITLE
Add Occurrence error

### ISSUE THREAD

**Issue by georges49** [alphasights/ember-calendar#38]
Hello,

When I click anywhere on the calendar, this error appears : 
**this.attrs.onAddOccurrence is not a function**

When I created the app a file named application.hbs was created in templates
so I added this code in it:

```handlebars
{{! app/templates/application.hbs }}
{{as-calendar
  title="Ember Calendar"
  occurrences=occurrences
  defaultTimeZoneQuery="New York|London|Dubai|Hong Kong"
  dayStartingTime="9:00"
  dayEndingTime="18:00"
  timeSlotDuration="00:30"
  onAddOccurrence="calendarAddOccurrence"
  onUpdateOccurrence="calendarUpdateOccurrence"
  onRemoveOccurrence="calendarRemoveOccurrence"}}
```

Then I generated a controller named application also with the command : ember generate controller application

and in app/controllers/application.js I added this code:

```js

export default Ember.Controller.extend({
  occurrences: Ember.A(),

  actions: {
    calendarAddOccurrence: function(occurrence) {
      this.get('occurrences').pushObject(Ember.Object.create({
        title: occurrence.get('title'),
        startsAt: occurrence.get('startsAt'),
        endsAt: occurrence.get('endsAt')
      }));
    },

    calendarUpdateOccurrence: function(occurrence, properties) {
      occurrence.setProperties(properties);
    },

    calendarRemoveOccurrence: function(occurrence) {
      this.get('occurrences').removeObject(occurrence);
    }
  }
});
```

I also imported these in app.scss
```scss
@import 'bower_components/paint/paint';
@import 'addons/ember-calendar/main';
```

Is there anything I'm doing wrong?

Thanks.

**Comment by Arkham** [comment]
hey @georges49 what happens if you rename your template to `index.hbs` and your controller to `index.js`?

**Comment by georges49** [comment]
Hi,
I renamed the files and the error persists.

**Comment by Arkham** [comment]
Here's my diff on a newly created ember app:

```diff
diff --git a/app/controllers/index.js b/app/controllers/index.js
new file mode 100644
index 0000000..75e66b0
--- /dev/null
+++ b/app/controllers/index.js
@@ -0,0 +1,23 @@
+import Ember from 'ember';
+
+export default Ember.Controller.extend({
+  occurrences: Ember.A(),
+
+  actions: {
+    calendarAddOccurrence: function(occurrence) {
+      this.get('occurrences').pushObject(Ember.Object.create({
+        title: occurrence.get('title'),
+        startsAt: occurrence.get('startsAt'),
+        endsAt: occurrence.get('endsAt')
+      }));
+    },
+
+    calendarUpdateOccurrence: function(occurrence, properties) {
+      occurrence.setProperties(properties);
+    },
+
+    calendarRemoveOccurrence: function(occurrence) {
+      this.get('occurrences').removeObject(occurrence);
+    }
+  }
+});
diff --git a/app/styles/app.scss b/app/styles/app.scss
new file mode 100644
index 0000000..569ac44
--- /dev/null
+++ b/app/styles/app.scss
@@ -0,0 +1,7 @@
+@import 'bower_components/fontawesome/scss/variables';
+@import 'bower_components/fontawesome/scss/path';
+@import 'bower_components/fontawesome/scss/mixins';
+@import 'bower_components/fontawesome/scss/icons';
+
+@import 'addons/ember-calendar/paint-core';
+@import 'addons/ember-calendar/main';
diff --git a/app/templates/index.hbs b/app/templates/index.hbs
new file mode 100644
index 0000000..2eacf2d
--- /dev/null
+++ b/app/templates/index.hbs
@@ -0,0 +1,10 @@
+{{as-calendar
+  title="Ember Calendar"
+  occurrences=occurrences
+  defaultTimeZoneQuery="New York|London|Dubai|Hong Kong"
+  dayStartingTime="9:00"
+  dayEndingTime="18:00"
+  timeSlotDuration="00:30"
+  onAddOccurrence=(action "calendarAddOccurrence")
+  onUpdateOccurrence=(action "calendarUpdateOccurrence")
+  onRemoveOccurrence=(action "calendarRemoveOccurrence")}}
diff --git a/bower.json b/bower.json
index 2a25bc6..356ec19 100644
--- a/bower.json
+++ b/bower.json
@@ -4,6 +4,10 @@
     "ember": "~2.3.1",
     "ember-cli-shims": "0.1.0",
     "ember-cli-test-loader": "0.2.2",
-    "ember-qunit-notifications": "0.1.0"
+    "ember-qunit-notifications": "0.1.0",
+    "interact": "1.2.5",
+    "jquery-simulate": "1.0.1",
+    "lodash": "3.10.0",
+    "fontawesome": "~4.5.0"
   }
 }
diff --git a/package.json b/package.json
index a5e9955..080cacc 100644
--- a/package.json
+++ b/package.json
@@ -20,7 +20,9 @@
   "license": "MIT",
   "devDependencies": {
     "broccoli-asset-rev": "^2.2.0",
+    "broccoli-sass": "0.7.0",
     "ember-ajax": "0.7.1",
+    "ember-calendar": "0.3.4",
     "ember-cli": "2.3.0",
     "ember-cli-app-version": "^1.0.0",
     "ember-cli-babel": "^5.1.5",
@@ -28,15 +30,20 @@
     "ember-cli-htmlbars": "^1.0.1",
     "ember-cli-htmlbars-inline-precompile": "^0.3.1",
     "ember-cli-inject-live-reload": "^1.3.1",
+    "ember-cli-moment-shim": "1.1.0",
     "ember-cli-qunit": "^1.2.1",
     "ember-cli-release": "0.2.8",
     "ember-cli-sri": "^2.0.0",
     "ember-cli-uglify": "^1.2.0",
+    "ember-component-inbound-actions": "0.0.4",
     "ember-data": "^2.3.0",
     "ember-disable-proxy-controllers": "^1.0.1",
     "ember-export-application-global": "^1.0.4",
     "ember-load-initializers": "^0.5.0",
+    "ember-moment": "6.0.0",
     "ember-resolver": "^2.0.3",
+    "ember-rl-dropdown": "0.7.0",
+    "liquid-fire": "0.21.3",
     "loader.js": "^4.0.0"
   }
 }
```

**Comment by georges49** [comment]
So the error is not appearing when you create a new app?
I have the same code you posted in the .js, .hbs and .scss files

**Here is the code I have in bower.json:**
{
  "name": "calendar-application",
  "dependencies": {
    "ember": "~2.4.1",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "interact": "1.2.5",
    "jquery-simulate": "1.0.1",
    "lodash": "3.10.0",
    "fontawesome": "~4.5.0",
    "paint": "0.9.5",
    "modernizr": "2.8.3",
    "spinjs": "2.0.2",
    "tooltipster": "3.3.0",
    "trackpad-scroll-emulator": "1.0.8"
  }
}

**And here is the code in package.json:**
{
  "name": "calendar-application",
  "version": "0.0.0",
  "description": "Small description for calendar-application goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "broccoli-sass": "0.7.0",
    "ember-ajax": "0.7.1",
    "ember-calendar": "0.3.4",
    "ember-cli": "2.4.1",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-moment-shim": "1.1.0",
    "ember-cli-paint": "1.13.8",
    "ember-cli-qunit": "^1.2.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-component-inbound-actions": "0.0.4",
    "ember-data": "^2.4.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-load-initializers": "^0.5.0",
    "ember-moment": "6.0.0",
    "ember-resolver": "^2.0.3",
    "ember-rl-dropdown": "0.7.0",
    "liquid-fire": "0.21.3",
    "loader.js": "^4.0.0"
  }
}

**Comment by Arkham** [comment]
Not sure then, the error usually means you are not defining an action in the controller associated to that template. Try checking for typos or creating an app from scratch.

**Comment by georges49** [comment]
I don't think it's typos as I copied and pasted the code from the read me.
And I did an app before this one and the error appeared there also.

Could it be something related to the version? A certain incompatibility?
I noticed that you have it "ember": "~2.3.1" in your bower.json file
Mine is "ember": "~2.4.1"

Thanks for your help anyway.

**Comment by Arkham** [comment]
I don't think so, because we've been using this addon in production since ember 1.13. I've pushed my working version to a new repo, so that you can try pulling and running `npm install && bower install && ember s`: https://github.com/Arkham/ember-calendar-test

**Comment by georges49** [comment]
So I create a new app and do this command:
ember install ember-calendar-test instead of ember install ember-calendar?

**Comment by Arkham** [comment]
No, just do this:

* `git clone https://github.com/Arkham/ember-calendar-test.git`
* `cd ember-calendar-test`
* `npm install && bower install && ember s`

**Comment by georges49** [comment]
That worked!
Many many thanks!!!

**Comment by Arkham** [comment]
Nice!
