### ISSUE TITLE
Uncaught Error: An action named 'changeTimeZone' was not found in <web@component:as-calendar/timetable::ember1306>.

### ISSUE THREAD

**Issue by chrismllr** [alphasights/ember-calendar#39]
Getting this after a clean `ember install ember-calendar`...  Seen this one before?

Seems to be a component looking for its top level `timetable` to pass it a closure action.

on v0.3.5

**Comment by Arkham** [comment]
hey @chrismllr I couldn't replicate this on a freshly created ember app. Could you provide some replication steps?

**Comment by Arkham** [comment]
Closing this for now.
