### ISSUE TITLE
arrows in blueprint throw error (cli@2.4.1)

### ISSUE THREAD

**Issue by crodriguez1a** [alphasights/ember-calendar#40]
`SyntaxError: Unexpected token )` when running ember install.

**Comment by Arkham** [comment]
Hey @crodriguez1a I couldn't replicate this error using ember cli 2.4.3 Do you have some replication steps?

**Comment by BenjaminHorn** [comment]
same here. I am on Ember CLI 2.3.0.

**Comment by Arkham** [comment]
@BenjaminHorn can you setup a new repo which reproduces the issue?

**Comment by BenjaminHorn** [comment]
@Arkham I'have just made a new repo (this time with ember-cli 2.4.0) and I tried to install the addon.
```
ember new ember-calendar-error
cd ember-calendar-error
ember install ember-calendar
```
![image](https://cloud.githubusercontent.com/assets/5570232/15741448/1a9f8e24-28ba-11e6-93a4-ac6588b27985.png)

https://github.com/alphasights/ember-calendar/blob/develop/blueprints/ember-calendar/index.js#L10

**Comment by crodriguez1a** [comment]
@Arkham Man, I'm sorry I never got back to you. Same issue as @BenjaminHorn. I'm not sure that babel is compiling when the blueprint is executed. Let me know if I can help.

**Comment by BenjaminHorn** [comment]
@Arkham  @crodriguez1a I think the problem is that in  `'use strict'` mode there is no arrow function. Anyway this seems to solve the problem:

```Javascript
/* jshint node: true */
'use strict';

module.exports = {
  normalizeEntityName: function() {},

  afterInstall: function() {
    var _this = this;
    return this.addAddonsToProject({
      packages: [{ name: 'ember-moment', target: '6.0.0' }]
    }).then(function() {
      return _this.addPackagesToProject([
        { name: 'broccoli-sass', target: '0.7.0' },
        { name: 'ember-component-inbound-actions', target: '0.0.4' },
        { name: 'ember-rl-dropdown', target: '0.7.0' },
        { name: 'liquid-fire', target: '0.21.3' }
      ]);
    }).then(function() {
      return _this.addBowerPackagesToProject([
        { name: 'interact', target: '1.2.5' },
        { name: 'jquery-simulate', target: '1.0.1' },
        { name: 'lodash', target: '3.10.0' },
        { name: 'fontawesome', target: '~4.5.0'}
      ]);
    });
  }
};
```

**Comment by Arkham** [comment]
Thanks for the report, I've release `0.3.8` which fixes this problem!
