### ISSUE TITLE
Build Problems

### ISSUE THREAD

**Issue by timoth3y** [alphasights/ember-calendar#42]
== Update == 
Deleting all tmp files and cloning repository did the trick. 

---------
Has anyone else run into this problem? 

ember install ember-calendar completes correctly but ember build results in the following error 
    app/styles/app.[scss|sass] does not exist

Of course, app/styles/app.scss does exist, and renaming to app/styles/app.saas produces the same error. 

Installing from git clone produces the same result.   Any ideas on how to resolve this?

Tim

**Comment by datajohnny** [comment]
+1

**Comment by mellatone** [comment]
+1

**Comment by Arkham** [comment]
There aren't enough replication info, closing this.
