### ISSUE TITLE
Build error - broccoli-sass

### ISSUE THREAD

**Issue by mciastek** [alphasights/ember-calendar#45]
Hi,

I installed your addon by `ember install ember-calendar` and run `ember serve`. Unfortunately I receive an error:
```bash
The Broccoli Plugin: [object Object] failed with:
undefined

The broccoli plugin was instantiated at: 
undefined
```

Ember version: `2.4.4`

I found that broccoli-sass cause that error. Can you switch to `ember-cli-sass` as Sass compiler?

Regards

**Comment by mciastek** [comment]
I created pull request to fix sass compiler bug. #46

**Comment by mellatone** [comment]
+1 this should be using `ember-cli-sass`

**Comment by Arkham** [comment]
Hey there, the issue is caused by incompatibilies between `broccoli-sass` and `ember-cli-sass`. I will spend some time investigating the best solution for this.

**Comment by Arkham** [comment]
Scratch that, I've release `0.3.9` which implements the change :)
