### ISSUE TITLE
failed to @extend "%dropdown-item"

### ISSUE THREAD

**Issue by mellatone** [alphasights/ember-calendar#48]
Where is `%dropdown-item` defined? It is referenced in the following code:

https://github.com/alphasights/ember-calendar/blob/develop/app/styles/addons/ember-calendar/components/as-calendar/_time-zone-select.scss#L52

```sass
  .search,
  .results {
      @extend %dropdown-item;
  }
```

I'm receiving this error:

```The Broccoli Plugin: [SassCompiler] failed with:
Error: ".as-calendar-time-zone-select .rl-dropdown .search" failed to @extend "%dropdown-item".
The selector "%dropdown-item" was not found.```

**Comment by prasannatm** [comment]
@mellatone Yes, I too had this problem. By changing the `%dropdown-item !optional;` fixes this issue for now.

**Comment by Arkham** [comment]
Thanks for the report, I've release `0.3.8` which fixes this problem!
