### ISSUE TITLE
Install failed. Could not find addon with name: ember-moment@6.0.0

### ISSUE THREAD

**Issue by machty** [alphasights/ember-calendar#54]
`ember install ember-calendar`

yields

```
Install failed. Could not find addon with name: ember-moment@6.0.0
```

```
$  ember --version
ember-cli: 2.6.0-beta.3
node: 5.11.1
os: darwin x64
```

**Comment by willrax** [comment]
Hey @machty, I don't seem to be able to replicate this using the same versions as you. I double checked, and that particular version of ember-moment seems to be real and still on npm.

Is there anything else that could help track down the issue? cc @Arkham

**Comment by cteeth** [comment]
Same problem here 

```
Install failed. Could not find addon with name: ember-moment@6.0.0
```

```
>ember --version
ember-cli: 2.6.0-beta.1
node: 5.11.0
os: win32 x64
```

**Comment by Arkham** [comment]
Mmm, that's really weird. @cteeth could you try running `npm install ember-moment@6.0.0` in your terminal? If that doesn't work, could you also try `npm install ember-moment@6.1.0`?

**Comment by cteeth** [comment]
The command `npm install ember-moment@6.0.0` work, but issue still here :-( 
```
PS C:\...\trunk> npm install ember-moment@6.0.0
PS C:\...\trunk> ember install ember-calendar
Installed packages for tooling via npm.
installing ember-calendar
  install addon ember-moment@6.0.0
Installed packages for tooling via npm.
Install failed. Could not find addon with name: ember-moment@6.0.0
PS C:\...\trunk>
```

**Comment by willrax** [comment]
@cteeth is this still an issue for you?

**Comment by willrax** [comment]
I'll close this for now, but please let me know if its still an issue :)
