### ISSUE TITLE
remove liquid fire

### ISSUE THREAD

**Issue by jamesdixon** [alphasights/ember-calendar#56]
Hi, just curious if you guys would be open to removing liquid fire? It seems like a pretty hefty dependency for a fading menu. I'd be more than happy to replace it with something similar.

**Comment by willrax** [comment]
Yep, I think this is something we could do. I think theres only one spot we use it for a crossfade.

**Comment by jamesdixon** [comment]
@willrax I already have a PR ready for this, but it goes hand-in-hand with #58.

**Comment by willrax** [comment]
ok cool :+1:

**Comment by willrax** [comment]
This should be removed now. The latest version still has it in the blueprint (oops), but we'll push a new version with it fully removed.
