### ISSUE TITLE
dependency cleanup

### ISSUE THREAD

**Issue by jamesdixon** [alphasights/ember-calendar#57]
There seems to be a number of dependencies, including `spinjs` and `tooltipster` that aren't used and are just bloating the add-on size.

**Note:** I'll be submitting some PRs for these, but just making note of them here for reference.

**Comment by willrax** [comment]
Hey @jamesdixon this would amazing. I've opened a PR to update some dependencies here: #60 and noticed a few that weren't being used as well.

**Comment by jamesdixon** [comment]
Hey @willrax, thanks for the reply!

I've actually been fairly hard at work with @marzubov on not only cleaning things up, but also adding a host of new features. We just need to get the documentation updated and then will be submitting a PR. Here's the branch if you'd like to check it out:

https://github.com/marzubov/ember-calendar

In a nutshell, this branch adds support for a day and month view, in addition to removing loads of dependencies.

**Comment by willrax** [comment]
Oh awesome! I'll check it out.

**Comment by willrax** [comment]
this should be all set.
