### ISSUE TITLE
not working properly on ember 2.8

### ISSUE THREAD

**Issue by carloszan** [alphasights/ember-calendar#59]
it returns this error

> could not find module ember-htmlbars/keywords/view

**Comment by willrax** [comment]
I've opened a PR to update the dependences and hopefully fix up this issue.

**Comment by Gorzas** [comment]
I've found the same bug. It is a bug in the library liquid-fire solved in the version 0.25. 

Related: https://github.com/ember-animation/liquid-fire/issues/484

**Comment by Subtletree** [comment]
@willrax keen to get these dependencies updated! : )

**Comment by willrax** [comment]
this should be updated and fixed now

**Comment by willrax** [comment]
in v0.4.0
